// Generated by gencpp from file sensehat_ros/Clear.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_CLEAR_H
#define SENSEHAT_ROS_MESSAGE_CLEAR_H

#include <ros/service_traits.h>


#include <sensehat_ros/ClearRequest.h>
#include <sensehat_ros/ClearResponse.h>


namespace sensehat_ros
{

struct Clear
{

typedef ClearRequest Request;
typedef ClearResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Clear
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::Clear > {
  static const char* value()
  {
    return "d1af828257b651791f41f5836fa55cda";
  }

  static const char* value(const ::sensehat_ros::Clear&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::Clear > {
  static const char* value()
  {
    return "sensehat_ros/Clear";
  }

  static const char* value(const ::sensehat_ros::Clear&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::ClearRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::Clear >
template<>
struct MD5Sum< ::sensehat_ros::ClearRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::Clear >::value();
  }
  static const char* value(const ::sensehat_ros::ClearRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::ClearRequest> should match
// service_traits::DataType< ::sensehat_ros::Clear >
template<>
struct DataType< ::sensehat_ros::ClearRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::Clear >::value();
  }
  static const char* value(const ::sensehat_ros::ClearRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::ClearResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::Clear >
template<>
struct MD5Sum< ::sensehat_ros::ClearResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::Clear >::value();
  }
  static const char* value(const ::sensehat_ros::ClearResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::ClearResponse> should match
// service_traits::DataType< ::sensehat_ros::Clear >
template<>
struct DataType< ::sensehat_ros::ClearResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::Clear >::value();
  }
  static const char* value(const ::sensehat_ros::ClearResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_CLEAR_H
