// Generated by gencpp from file sensehat_ros/GetCompassResponse.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETCOMPASSRESPONSE_H
#define SENSEHAT_ROS_MESSAGE_GETCOMPASSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensehat_ros
{
template <class ContainerAllocator>
struct GetCompassResponse_
{
  typedef GetCompassResponse_<ContainerAllocator> Type;

  GetCompassResponse_()
    : compass(0.0)  {
    }
  GetCompassResponse_(const ContainerAllocator& _alloc)
    : compass(0.0)  {
  (void)_alloc;
    }



   typedef double _compass_type;
  _compass_type compass;





  typedef boost::shared_ptr< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetCompassResponse_

typedef ::sensehat_ros::GetCompassResponse_<std::allocator<void> > GetCompassResponse;

typedef boost::shared_ptr< ::sensehat_ros::GetCompassResponse > GetCompassResponsePtr;
typedef boost::shared_ptr< ::sensehat_ros::GetCompassResponse const> GetCompassResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensehat_ros::GetCompassResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensehat_ros::GetCompassResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetCompassResponse_<ContainerAllocator2> & rhs)
{
  return lhs.compass == rhs.compass;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensehat_ros::GetCompassResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetCompassResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensehat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c9cf463517905dca2521bd4ad9d8bf6";
  }

  static const char* value(const ::sensehat_ros::GetCompassResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c9cf463517905dcULL;
  static const uint64_t static_value2 = 0xa2521bd4ad9d8bf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensehat_ros/GetCompassResponse";
  }

  static const char* value(const ::sensehat_ros::GetCompassResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 compass\n"
;
  }

  static const char* value(const ::sensehat_ros::GetCompassResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.compass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCompassResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensehat_ros::GetCompassResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensehat_ros::GetCompassResponse_<ContainerAllocator>& v)
  {
    s << indent << "compass: ";
    Printer<double>::stream(s, indent + "  ", v.compass);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETCOMPASSRESPONSE_H
