// Generated by gencpp from file sensehat_ros/GetHumidityResponse.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETHUMIDITYRESPONSE_H
#define SENSEHAT_ROS_MESSAGE_GETHUMIDITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensehat_ros
{
template <class ContainerAllocator>
struct GetHumidityResponse_
{
  typedef GetHumidityResponse_<ContainerAllocator> Type;

  GetHumidityResponse_()
    : humidity(0.0)  {
    }
  GetHumidityResponse_(const ContainerAllocator& _alloc)
    : humidity(0.0)  {
  (void)_alloc;
    }



   typedef double _humidity_type;
  _humidity_type humidity;





  typedef boost::shared_ptr< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHumidityResponse_

typedef ::sensehat_ros::GetHumidityResponse_<std::allocator<void> > GetHumidityResponse;

typedef boost::shared_ptr< ::sensehat_ros::GetHumidityResponse > GetHumidityResponsePtr;
typedef boost::shared_ptr< ::sensehat_ros::GetHumidityResponse const> GetHumidityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensehat_ros::GetHumidityResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetHumidityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.humidity == rhs.humidity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensehat_ros::GetHumidityResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetHumidityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensehat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8a984e8229c8179cd55100369522f34";
  }

  static const char* value(const ::sensehat_ros::GetHumidityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8a984e8229c8179ULL;
  static const uint64_t static_value2 = 0xcd55100369522f34ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensehat_ros/GetHumidityResponse";
  }

  static const char* value(const ::sensehat_ros::GetHumidityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 humidity\n"
;
  }

  static const char* value(const ::sensehat_ros::GetHumidityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.humidity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHumidityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensehat_ros::GetHumidityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensehat_ros::GetHumidityResponse_<ContainerAllocator>& v)
  {
    s << indent << "humidity: ";
    Printer<double>::stream(s, indent + "  ", v.humidity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETHUMIDITYRESPONSE_H
