// Generated by gencpp from file sensehat_ros/GetIMURequest.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETIMUREQUEST_H
#define SENSEHAT_ROS_MESSAGE_GETIMUREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensehat_ros
{
template <class ContainerAllocator>
struct GetIMURequest_
{
  typedef GetIMURequest_<ContainerAllocator> Type;

  GetIMURequest_()
    : mode()  {
    }
  GetIMURequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::sensehat_ros::GetIMURequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensehat_ros::GetIMURequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetIMURequest_

typedef ::sensehat_ros::GetIMURequest_<std::allocator<void> > GetIMURequest;

typedef boost::shared_ptr< ::sensehat_ros::GetIMURequest > GetIMURequestPtr;
typedef boost::shared_ptr< ::sensehat_ros::GetIMURequest const> GetIMURequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensehat_ros::GetIMURequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensehat_ros::GetIMURequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensehat_ros::GetIMURequest_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetIMURequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensehat_ros::GetIMURequest_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetIMURequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensehat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetIMURequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetIMURequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetIMURequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetIMURequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetIMURequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetIMURequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensehat_ros::GetIMURequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e84dc3ad5dc323bb64f0aca01c2d1eef";
  }

  static const char* value(const ::sensehat_ros::GetIMURequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe84dc3ad5dc323bbULL;
  static const uint64_t static_value2 = 0x64f0aca01c2d1eefULL;
};

template<class ContainerAllocator>
struct DataType< ::sensehat_ros::GetIMURequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensehat_ros/GetIMURequest";
  }

  static const char* value(const ::sensehat_ros::GetIMURequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensehat_ros::GetIMURequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# queries Sense HAT IMU sensor. Warning: not allowed when imu_publishing=True due to potential set_imu_config interference\n"
"string mode\n"
;
  }

  static const char* value(const ::sensehat_ros::GetIMURequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensehat_ros::GetIMURequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIMURequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensehat_ros::GetIMURequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensehat_ros::GetIMURequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETIMUREQUEST_H
