// Generated by gencpp from file sensehat_ros/GetTemperature.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETTEMPERATURE_H
#define SENSEHAT_ROS_MESSAGE_GETTEMPERATURE_H

#include <ros/service_traits.h>


#include <sensehat_ros/GetTemperatureRequest.h>
#include <sensehat_ros/GetTemperatureResponse.h>


namespace sensehat_ros
{

struct GetTemperature
{

typedef GetTemperatureRequest Request;
typedef GetTemperatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTemperature
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::GetTemperature > {
  static const char* value()
  {
    return "3d36f909fc0be819c991c4abdee75a2b";
  }

  static const char* value(const ::sensehat_ros::GetTemperature&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::GetTemperature > {
  static const char* value()
  {
    return "sensehat_ros/GetTemperature";
  }

  static const char* value(const ::sensehat_ros::GetTemperature&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::GetTemperatureRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::GetTemperature >
template<>
struct MD5Sum< ::sensehat_ros::GetTemperatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::GetTemperature >::value();
  }
  static const char* value(const ::sensehat_ros::GetTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::GetTemperatureRequest> should match
// service_traits::DataType< ::sensehat_ros::GetTemperature >
template<>
struct DataType< ::sensehat_ros::GetTemperatureRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::GetTemperature >::value();
  }
  static const char* value(const ::sensehat_ros::GetTemperatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::GetTemperatureResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::GetTemperature >
template<>
struct MD5Sum< ::sensehat_ros::GetTemperatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::GetTemperature >::value();
  }
  static const char* value(const ::sensehat_ros::GetTemperatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::GetTemperatureResponse> should match
// service_traits::DataType< ::sensehat_ros::GetTemperature >
template<>
struct DataType< ::sensehat_ros::GetTemperatureResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::GetTemperature >::value();
  }
  static const char* value(const ::sensehat_ros::GetTemperatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETTEMPERATURE_H
