// Generated by gencpp from file sensehat_ros/SetPixels.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_SETPIXELS_H
#define SENSEHAT_ROS_MESSAGE_SETPIXELS_H

#include <ros/service_traits.h>


#include <sensehat_ros/SetPixelsRequest.h>
#include <sensehat_ros/SetPixelsResponse.h>


namespace sensehat_ros
{

struct SetPixels
{

typedef SetPixelsRequest Request;
typedef SetPixelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPixels
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::SetPixels > {
  static const char* value()
  {
    return "b50ba911a4776c69c8ff57eb35b1d884";
  }

  static const char* value(const ::sensehat_ros::SetPixels&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::SetPixels > {
  static const char* value()
  {
    return "sensehat_ros/SetPixels";
  }

  static const char* value(const ::sensehat_ros::SetPixels&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::SetPixelsRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::SetPixels >
template<>
struct MD5Sum< ::sensehat_ros::SetPixelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::SetPixels >::value();
  }
  static const char* value(const ::sensehat_ros::SetPixelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::SetPixelsRequest> should match
// service_traits::DataType< ::sensehat_ros::SetPixels >
template<>
struct DataType< ::sensehat_ros::SetPixelsRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::SetPixels >::value();
  }
  static const char* value(const ::sensehat_ros::SetPixelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::SetPixelsResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::SetPixels >
template<>
struct MD5Sum< ::sensehat_ros::SetPixelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::SetPixels >::value();
  }
  static const char* value(const ::sensehat_ros::SetPixelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::SetPixelsResponse> should match
// service_traits::DataType< ::sensehat_ros::SetPixels >
template<>
struct DataType< ::sensehat_ros::SetPixelsResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::SetPixels >::value();
  }
  static const char* value(const ::sensehat_ros::SetPixelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_SETPIXELS_H
