// Generated by gencpp from file sensehat_ros/ShowLetter.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_SHOWLETTER_H
#define SENSEHAT_ROS_MESSAGE_SHOWLETTER_H

#include <ros/service_traits.h>


#include <sensehat_ros/ShowLetterRequest.h>
#include <sensehat_ros/ShowLetterResponse.h>


namespace sensehat_ros
{

struct ShowLetter
{

typedef ShowLetterRequest Request;
typedef ShowLetterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShowLetter
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::ShowLetter > {
  static const char* value()
  {
    return "2e9a1baf1bf4e3e4917790796f05c5e4";
  }

  static const char* value(const ::sensehat_ros::ShowLetter&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::ShowLetter > {
  static const char* value()
  {
    return "sensehat_ros/ShowLetter";
  }

  static const char* value(const ::sensehat_ros::ShowLetter&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::ShowLetterRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::ShowLetter >
template<>
struct MD5Sum< ::sensehat_ros::ShowLetterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::ShowLetter >::value();
  }
  static const char* value(const ::sensehat_ros::ShowLetterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::ShowLetterRequest> should match
// service_traits::DataType< ::sensehat_ros::ShowLetter >
template<>
struct DataType< ::sensehat_ros::ShowLetterRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::ShowLetter >::value();
  }
  static const char* value(const ::sensehat_ros::ShowLetterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::ShowLetterResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::ShowLetter >
template<>
struct MD5Sum< ::sensehat_ros::ShowLetterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::ShowLetter >::value();
  }
  static const char* value(const ::sensehat_ros::ShowLetterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::ShowLetterResponse> should match
// service_traits::DataType< ::sensehat_ros::ShowLetter >
template<>
struct DataType< ::sensehat_ros::ShowLetterResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::ShowLetter >::value();
  }
  static const char* value(const ::sensehat_ros::ShowLetterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_SHOWLETTER_H
