// Generated by gencpp from file sensehat_ros/ShowMessage.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_SHOWMESSAGE_H
#define SENSEHAT_ROS_MESSAGE_SHOWMESSAGE_H

#include <ros/service_traits.h>


#include <sensehat_ros/ShowMessageRequest.h>
#include <sensehat_ros/ShowMessageResponse.h>


namespace sensehat_ros
{

struct ShowMessage
{

typedef ShowMessageRequest Request;
typedef ShowMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShowMessage
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::ShowMessage > {
  static const char* value()
  {
    return "4db536e63c8164b2d79316cbb359b0f0";
  }

  static const char* value(const ::sensehat_ros::ShowMessage&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::ShowMessage > {
  static const char* value()
  {
    return "sensehat_ros/ShowMessage";
  }

  static const char* value(const ::sensehat_ros::ShowMessage&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::ShowMessageRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::ShowMessage >
template<>
struct MD5Sum< ::sensehat_ros::ShowMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::ShowMessage >::value();
  }
  static const char* value(const ::sensehat_ros::ShowMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::ShowMessageRequest> should match
// service_traits::DataType< ::sensehat_ros::ShowMessage >
template<>
struct DataType< ::sensehat_ros::ShowMessageRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::ShowMessage >::value();
  }
  static const char* value(const ::sensehat_ros::ShowMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::ShowMessageResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::ShowMessage >
template<>
struct MD5Sum< ::sensehat_ros::ShowMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::ShowMessage >::value();
  }
  static const char* value(const ::sensehat_ros::ShowMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::ShowMessageResponse> should match
// service_traits::DataType< ::sensehat_ros::ShowMessage >
template<>
struct DataType< ::sensehat_ros::ShowMessageResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::ShowMessage >::value();
  }
  static const char* value(const ::sensehat_ros::ShowMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_SHOWMESSAGE_H
