// Generated by gencpp from file sensehat_ros/ShowLetterRequest.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_SHOWLETTERREQUEST_H
#define SENSEHAT_ROS_MESSAGE_SHOWLETTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensehat_ros
{
template <class ContainerAllocator>
struct ShowLetterRequest_
{
  typedef ShowLetterRequest_<ContainerAllocator> Type;

  ShowLetterRequest_()
    : text()
    , text_colour()
    , back_colour()
    , duration(0.0)  {
      text_colour.assign(0);

      back_colour.assign(0);
  }
  ShowLetterRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , text_colour()
    , back_colour()
    , duration(0.0)  {
  (void)_alloc;
      text_colour.assign(0);

      back_colour.assign(0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;

   typedef boost::array<int16_t, 3>  _text_colour_type;
  _text_colour_type text_colour;

   typedef boost::array<int16_t, 3>  _back_colour_type;
  _back_colour_type back_colour;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShowLetterRequest_

typedef ::sensehat_ros::ShowLetterRequest_<std::allocator<void> > ShowLetterRequest;

typedef boost::shared_ptr< ::sensehat_ros::ShowLetterRequest > ShowLetterRequestPtr;
typedef boost::shared_ptr< ::sensehat_ros::ShowLetterRequest const> ShowLetterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensehat_ros::ShowLetterRequest_<ContainerAllocator1> & lhs, const ::sensehat_ros::ShowLetterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text &&
    lhs.text_colour == rhs.text_colour &&
    lhs.back_colour == rhs.back_colour &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensehat_ros::ShowLetterRequest_<ContainerAllocator1> & lhs, const ::sensehat_ros::ShowLetterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensehat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e9a1baf1bf4e3e4917790796f05c5e4";
  }

  static const char* value(const ::sensehat_ros::ShowLetterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e9a1baf1bf4e3e4ULL;
  static const uint64_t static_value2 = 0x917790796f05c5e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensehat_ros/ShowLetterRequest";
  }

  static const char* value(const ::sensehat_ros::ShowLetterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# shows a letter on the LED matrix and waits for the specified amount of seconds\n"
"string text\n"
"int16[3] text_colour\n"
"int16[3] back_colour\n"
"float64 duration\n"
;
  }

  static const char* value(const ::sensehat_ros::ShowLetterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.text_colour);
      stream.next(m.back_colour);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShowLetterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensehat_ros::ShowLetterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensehat_ros::ShowLetterRequest_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
    s << indent << "text_colour[]" << std::endl;
    for (size_t i = 0; i < v.text_colour.size(); ++i)
    {
      s << indent << "  text_colour[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.text_colour[i]);
    }
    s << indent << "back_colour[]" << std::endl;
    for (size_t i = 0; i < v.back_colour.size(); ++i)
    {
      s << indent << "  back_colour[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.back_colour[i]);
    }
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_SHOWLETTERREQUEST_H
