// Generated by gencpp from file sensehat_ros/SwitchLowLight.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_SWITCHLOWLIGHT_H
#define SENSEHAT_ROS_MESSAGE_SWITCHLOWLIGHT_H

#include <ros/service_traits.h>


#include <sensehat_ros/SwitchLowLightRequest.h>
#include <sensehat_ros/SwitchLowLightResponse.h>


namespace sensehat_ros
{

struct SwitchLowLight
{

typedef SwitchLowLightRequest Request;
typedef SwitchLowLightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchLowLight
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::SwitchLowLight > {
  static const char* value()
  {
    return "28b22af2b341afecad6c7499580b70d4";
  }

  static const char* value(const ::sensehat_ros::SwitchLowLight&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::SwitchLowLight > {
  static const char* value()
  {
    return "sensehat_ros/SwitchLowLight";
  }

  static const char* value(const ::sensehat_ros::SwitchLowLight&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::SwitchLowLightRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::SwitchLowLight >
template<>
struct MD5Sum< ::sensehat_ros::SwitchLowLightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::SwitchLowLight >::value();
  }
  static const char* value(const ::sensehat_ros::SwitchLowLightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::SwitchLowLightRequest> should match
// service_traits::DataType< ::sensehat_ros::SwitchLowLight >
template<>
struct DataType< ::sensehat_ros::SwitchLowLightRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::SwitchLowLight >::value();
  }
  static const char* value(const ::sensehat_ros::SwitchLowLightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::SwitchLowLightResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::SwitchLowLight >
template<>
struct MD5Sum< ::sensehat_ros::SwitchLowLightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::SwitchLowLight >::value();
  }
  static const char* value(const ::sensehat_ros::SwitchLowLightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::SwitchLowLightResponse> should match
// service_traits::DataType< ::sensehat_ros::SwitchLowLight >
template<>
struct DataType< ::sensehat_ros::SwitchLowLightResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::SwitchLowLight >::value();
  }
  static const char* value(const ::sensehat_ros::SwitchLowLightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_SWITCHLOWLIGHT_H
