// Generated by gencpp from file sensehat_ros/EmulateStick.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_EMULATESTICK_H
#define SENSEHAT_ROS_MESSAGE_EMULATESTICK_H

#include <ros/service_traits.h>


#include <sensehat_ros/EmulateStickRequest.h>
#include <sensehat_ros/EmulateStickResponse.h>


namespace sensehat_ros
{

struct EmulateStick
{

typedef EmulateStickRequest Request;
typedef EmulateStickResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmulateStick
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::EmulateStick > {
  static const char* value()
  {
    return "ea0fd98be9330a0f4043bbdfe1d139c9";
  }

  static const char* value(const ::sensehat_ros::EmulateStick&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::EmulateStick > {
  static const char* value()
  {
    return "sensehat_ros/EmulateStick";
  }

  static const char* value(const ::sensehat_ros::EmulateStick&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::EmulateStickRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::EmulateStick >
template<>
struct MD5Sum< ::sensehat_ros::EmulateStickRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::EmulateStick >::value();
  }
  static const char* value(const ::sensehat_ros::EmulateStickRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::EmulateStickRequest> should match
// service_traits::DataType< ::sensehat_ros::EmulateStick >
template<>
struct DataType< ::sensehat_ros::EmulateStickRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::EmulateStick >::value();
  }
  static const char* value(const ::sensehat_ros::EmulateStickRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::EmulateStickResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::EmulateStick >
template<>
struct MD5Sum< ::sensehat_ros::EmulateStickResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::EmulateStick >::value();
  }
  static const char* value(const ::sensehat_ros::EmulateStickResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::EmulateStickResponse> should match
// service_traits::DataType< ::sensehat_ros::EmulateStick >
template<>
struct DataType< ::sensehat_ros::EmulateStickResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::EmulateStick >::value();
  }
  static const char* value(const ::sensehat_ros::EmulateStickResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_EMULATESTICK_H
