// Generated by gencpp from file sensehat_ros/EmulateStickRequest.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_EMULATESTICKREQUEST_H
#define SENSEHAT_ROS_MESSAGE_EMULATESTICKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensehat_ros
{
template <class ContainerAllocator>
struct EmulateStickRequest_
{
  typedef EmulateStickRequest_<ContainerAllocator> Type;

  EmulateStickRequest_()
    : direction()
    , action()  {
    }
  EmulateStickRequest_(const ContainerAllocator& _alloc)
    : direction(_alloc)
    , action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EmulateStickRequest_

typedef ::sensehat_ros::EmulateStickRequest_<std::allocator<void> > EmulateStickRequest;

typedef boost::shared_ptr< ::sensehat_ros::EmulateStickRequest > EmulateStickRequestPtr;
typedef boost::shared_ptr< ::sensehat_ros::EmulateStickRequest const> EmulateStickRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensehat_ros::EmulateStickRequest_<ContainerAllocator1> & lhs, const ::sensehat_ros::EmulateStickRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensehat_ros::EmulateStickRequest_<ContainerAllocator1> & lhs, const ::sensehat_ros::EmulateStickRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensehat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea0fd98be9330a0f4043bbdfe1d139c9";
  }

  static const char* value(const ::sensehat_ros::EmulateStickRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea0fd98be9330a0fULL;
  static const uint64_t static_value2 = 0x4043bbdfe1d139c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensehat_ros/EmulateStickRequest";
  }

  static const char* value(const ::sensehat_ros::EmulateStickRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# remotely triggers a stick event without interacting with the Stick device\n"
"string direction\n"
"string action\n"
;
  }

  static const char* value(const ::sensehat_ros::EmulateStickRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmulateStickRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensehat_ros::EmulateStickRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensehat_ros::EmulateStickRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_EMULATESTICKREQUEST_H
