// Generated by gencpp from file sensehat_ros/Environmental.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_ENVIRONMENTAL_H
#define SENSEHAT_ROS_MESSAGE_ENVIRONMENTAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sensehat_ros
{
template <class ContainerAllocator>
struct Environmental_
{
  typedef Environmental_<ContainerAllocator> Type;

  Environmental_()
    : header()
    , humidity(0.0)
    , temperature_from_humidity(0.0)
    , temperature_from_pressure(0.0)
    , pressure(0.0)  {
    }
  Environmental_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , humidity(0.0)
    , temperature_from_humidity(0.0)
    , temperature_from_pressure(0.0)
    , pressure(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _humidity_type;
  _humidity_type humidity;

   typedef double _temperature_from_humidity_type;
  _temperature_from_humidity_type temperature_from_humidity;

   typedef double _temperature_from_pressure_type;
  _temperature_from_pressure_type temperature_from_pressure;

   typedef double _pressure_type;
  _pressure_type pressure;





  typedef boost::shared_ptr< ::sensehat_ros::Environmental_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensehat_ros::Environmental_<ContainerAllocator> const> ConstPtr;

}; // struct Environmental_

typedef ::sensehat_ros::Environmental_<std::allocator<void> > Environmental;

typedef boost::shared_ptr< ::sensehat_ros::Environmental > EnvironmentalPtr;
typedef boost::shared_ptr< ::sensehat_ros::Environmental const> EnvironmentalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensehat_ros::Environmental_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensehat_ros::Environmental_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensehat_ros::Environmental_<ContainerAllocator1> & lhs, const ::sensehat_ros::Environmental_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.humidity == rhs.humidity &&
    lhs.temperature_from_humidity == rhs.temperature_from_humidity &&
    lhs.temperature_from_pressure == rhs.temperature_from_pressure &&
    lhs.pressure == rhs.pressure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensehat_ros::Environmental_<ContainerAllocator1> & lhs, const ::sensehat_ros::Environmental_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensehat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::Environmental_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::Environmental_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::Environmental_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::Environmental_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::Environmental_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::Environmental_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensehat_ros::Environmental_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68c3afb26b37144add6301d7bd68f356";
  }

  static const char* value(const ::sensehat_ros::Environmental_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68c3afb26b37144aULL;
  static const uint64_t static_value2 = 0xdd6301d7bd68f356ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensehat_ros::Environmental_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensehat_ros/Environmental";
  }

  static const char* value(const ::sensehat_ros::Environmental_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensehat_ros::Environmental_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Hold data extracted from Sense HAT environmental sensors (humidity and pressure)\n"
"Header header\n"
"# Percentage of relative humidity \n"
"float64 humidity\n"
"# Temperature in degrees Celsius from the humidity sensor\n"
"float64 temperature_from_humidity\n"
"# Temperature in degrees Celsius from the pressure sensor\n"
"float64 temperature_from_pressure\n"
"# Pressure in Millibars\n"
"float64 pressure\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sensehat_ros::Environmental_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensehat_ros::Environmental_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.humidity);
      stream.next(m.temperature_from_humidity);
      stream.next(m.temperature_from_pressure);
      stream.next(m.pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Environmental_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensehat_ros::Environmental_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensehat_ros::Environmental_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "humidity: ";
    Printer<double>::stream(s, indent + "  ", v.humidity);
    s << indent << "temperature_from_humidity: ";
    Printer<double>::stream(s, indent + "  ", v.temperature_from_humidity);
    s << indent << "temperature_from_pressure: ";
    Printer<double>::stream(s, indent + "  ", v.temperature_from_pressure);
    s << indent << "pressure: ";
    Printer<double>::stream(s, indent + "  ", v.pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_ENVIRONMENTAL_H
