// Generated by gencpp from file sensehat_ros/GetEnvironmentalResponse.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETENVIRONMENTALRESPONSE_H
#define SENSEHAT_ROS_MESSAGE_GETENVIRONMENTALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensehat_ros/Environmental.h>

namespace sensehat_ros
{
template <class ContainerAllocator>
struct GetEnvironmentalResponse_
{
  typedef GetEnvironmentalResponse_<ContainerAllocator> Type;

  GetEnvironmentalResponse_()
    : environmental()  {
    }
  GetEnvironmentalResponse_(const ContainerAllocator& _alloc)
    : environmental(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensehat_ros::Environmental_<ContainerAllocator>  _environmental_type;
  _environmental_type environmental;





  typedef boost::shared_ptr< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetEnvironmentalResponse_

typedef ::sensehat_ros::GetEnvironmentalResponse_<std::allocator<void> > GetEnvironmentalResponse;

typedef boost::shared_ptr< ::sensehat_ros::GetEnvironmentalResponse > GetEnvironmentalResponsePtr;
typedef boost::shared_ptr< ::sensehat_ros::GetEnvironmentalResponse const> GetEnvironmentalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.environmental == rhs.environmental;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensehat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59eda83d9763a27d7339a28eb5d390bf";
  }

  static const char* value(const ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59eda83d9763a27dULL;
  static const uint64_t static_value2 = 0x7339a28eb5d390bfULL;
};

template<class ContainerAllocator>
struct DataType< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensehat_ros/GetEnvironmentalResponse";
  }

  static const char* value(const ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Environmental environmental\n"
"\n"
"================================================================================\n"
"MSG: sensehat_ros/Environmental\n"
"# Hold data extracted from Sense HAT environmental sensors (humidity and pressure)\n"
"Header header\n"
"# Percentage of relative humidity \n"
"float64 humidity\n"
"# Temperature in degrees Celsius from the humidity sensor\n"
"float64 temperature_from_humidity\n"
"# Temperature in degrees Celsius from the pressure sensor\n"
"float64 temperature_from_pressure\n"
"# Pressure in Millibars\n"
"float64 pressure\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.environmental);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEnvironmentalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensehat_ros::GetEnvironmentalResponse_<ContainerAllocator>& v)
  {
    s << indent << "environmental: ";
    s << std::endl;
    Printer< ::sensehat_ros::Environmental_<ContainerAllocator> >::stream(s, indent + "  ", v.environmental);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETENVIRONMENTALRESPONSE_H
