// Generated by gencpp from file sensehat_ros/GetEnvironmental.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETENVIRONMENTAL_H
#define SENSEHAT_ROS_MESSAGE_GETENVIRONMENTAL_H

#include <ros/service_traits.h>


#include <sensehat_ros/GetEnvironmentalRequest.h>
#include <sensehat_ros/GetEnvironmentalResponse.h>


namespace sensehat_ros
{

struct GetEnvironmental
{

typedef GetEnvironmentalRequest Request;
typedef GetEnvironmentalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEnvironmental
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::GetEnvironmental > {
  static const char* value()
  {
    return "59eda83d9763a27d7339a28eb5d390bf";
  }

  static const char* value(const ::sensehat_ros::GetEnvironmental&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::GetEnvironmental > {
  static const char* value()
  {
    return "sensehat_ros/GetEnvironmental";
  }

  static const char* value(const ::sensehat_ros::GetEnvironmental&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::GetEnvironmentalRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::GetEnvironmental >
template<>
struct MD5Sum< ::sensehat_ros::GetEnvironmentalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::GetEnvironmental >::value();
  }
  static const char* value(const ::sensehat_ros::GetEnvironmentalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::GetEnvironmentalRequest> should match
// service_traits::DataType< ::sensehat_ros::GetEnvironmental >
template<>
struct DataType< ::sensehat_ros::GetEnvironmentalRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::GetEnvironmental >::value();
  }
  static const char* value(const ::sensehat_ros::GetEnvironmentalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::GetEnvironmentalResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::GetEnvironmental >
template<>
struct MD5Sum< ::sensehat_ros::GetEnvironmentalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::GetEnvironmental >::value();
  }
  static const char* value(const ::sensehat_ros::GetEnvironmentalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::GetEnvironmentalResponse> should match
// service_traits::DataType< ::sensehat_ros::GetEnvironmental >
template<>
struct DataType< ::sensehat_ros::GetEnvironmentalResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::GetEnvironmental >::value();
  }
  static const char* value(const ::sensehat_ros::GetEnvironmentalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETENVIRONMENTAL_H
