// Generated by gencpp from file sensehat_ros/GetHumidity.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETHUMIDITY_H
#define SENSEHAT_ROS_MESSAGE_GETHUMIDITY_H

#include <ros/service_traits.h>


#include <sensehat_ros/GetHumidityRequest.h>
#include <sensehat_ros/GetHumidityResponse.h>


namespace sensehat_ros
{

struct GetHumidity
{

typedef GetHumidityRequest Request;
typedef GetHumidityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHumidity
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::GetHumidity > {
  static const char* value()
  {
    return "c8a984e8229c8179cd55100369522f34";
  }

  static const char* value(const ::sensehat_ros::GetHumidity&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::GetHumidity > {
  static const char* value()
  {
    return "sensehat_ros/GetHumidity";
  }

  static const char* value(const ::sensehat_ros::GetHumidity&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::GetHumidityRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::GetHumidity >
template<>
struct MD5Sum< ::sensehat_ros::GetHumidityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::GetHumidity >::value();
  }
  static const char* value(const ::sensehat_ros::GetHumidityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::GetHumidityRequest> should match
// service_traits::DataType< ::sensehat_ros::GetHumidity >
template<>
struct DataType< ::sensehat_ros::GetHumidityRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::GetHumidity >::value();
  }
  static const char* value(const ::sensehat_ros::GetHumidityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::GetHumidityResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::GetHumidity >
template<>
struct MD5Sum< ::sensehat_ros::GetHumidityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::GetHumidity >::value();
  }
  static const char* value(const ::sensehat_ros::GetHumidityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::GetHumidityResponse> should match
// service_traits::DataType< ::sensehat_ros::GetHumidity >
template<>
struct DataType< ::sensehat_ros::GetHumidityResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::GetHumidity >::value();
  }
  static const char* value(const ::sensehat_ros::GetHumidityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETHUMIDITY_H
