// Generated by gencpp from file sensehat_ros/GetIMUResponse.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETIMURESPONSE_H
#define SENSEHAT_ROS_MESSAGE_GETIMURESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensehat_ros/IMU.h>

namespace sensehat_ros
{
template <class ContainerAllocator>
struct GetIMUResponse_
{
  typedef GetIMUResponse_<ContainerAllocator> Type;

  GetIMUResponse_()
    : imu()  {
    }
  GetIMUResponse_(const ContainerAllocator& _alloc)
    : imu(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensehat_ros::IMU_<ContainerAllocator>  _imu_type;
  _imu_type imu;





  typedef boost::shared_ptr< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetIMUResponse_

typedef ::sensehat_ros::GetIMUResponse_<std::allocator<void> > GetIMUResponse;

typedef boost::shared_ptr< ::sensehat_ros::GetIMUResponse > GetIMUResponsePtr;
typedef boost::shared_ptr< ::sensehat_ros::GetIMUResponse const> GetIMUResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensehat_ros::GetIMUResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensehat_ros::GetIMUResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetIMUResponse_<ContainerAllocator2> & rhs)
{
  return lhs.imu == rhs.imu;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensehat_ros::GetIMUResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetIMUResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensehat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a973cf17193e984943c6d1b80a5c4df";
  }

  static const char* value(const ::sensehat_ros::GetIMUResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a973cf17193e984ULL;
  static const uint64_t static_value2 = 0x943c6d1b80a5c4dfULL;
};

template<class ContainerAllocator>
struct DataType< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensehat_ros/GetIMUResponse";
  }

  static const char* value(const ::sensehat_ros::GetIMUResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "IMU imu\n"
"\n"
"================================================================================\n"
"MSG: sensehat_ros/IMU\n"
"# Hold data extracted from the Sense HAT IMU sensor.\n"
"# Fields x, y and z assume different meaning depending on the selected mode.\n"
"# Modes ending with \"_rpy\" assign (roll, pitch, yaw) values to (x, y, z). \n"
"Header header\n"
"# Indicates the API function used to extract data from the IMU. Valid values are:\n"
"#   * get_orientation_radians_rpy\n"
"#   * get_orientation_degrees_rpy\n"
"#   * get_compass_raw_xyz\n"
"#   * get_gyroscope_rpy\n"
"#   * get_gyroscope_raw_xyz\n"
"#   * get_accelerometer_rpy\n"
"#   * get_accelerometer_raw_xyzstring mode\n"
"string mode\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sensehat_ros::GetIMUResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imu);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetIMUResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensehat_ros::GetIMUResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensehat_ros::GetIMUResponse_<ContainerAllocator>& v)
  {
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::sensehat_ros::IMU_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETIMURESPONSE_H
