// Generated by gencpp from file sensehat_ros/GetPressure.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETPRESSURE_H
#define SENSEHAT_ROS_MESSAGE_GETPRESSURE_H

#include <ros/service_traits.h>


#include <sensehat_ros/GetPressureRequest.h>
#include <sensehat_ros/GetPressureResponse.h>


namespace sensehat_ros
{

struct GetPressure
{

typedef GetPressureRequest Request;
typedef GetPressureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPressure
} // namespace sensehat_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensehat_ros::GetPressure > {
  static const char* value()
  {
    return "96df4beb6a408783cb39b2bac74b5b16";
  }

  static const char* value(const ::sensehat_ros::GetPressure&) { return value(); }
};

template<>
struct DataType< ::sensehat_ros::GetPressure > {
  static const char* value()
  {
    return "sensehat_ros/GetPressure";
  }

  static const char* value(const ::sensehat_ros::GetPressure&) { return value(); }
};


// service_traits::MD5Sum< ::sensehat_ros::GetPressureRequest> should match
// service_traits::MD5Sum< ::sensehat_ros::GetPressure >
template<>
struct MD5Sum< ::sensehat_ros::GetPressureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::GetPressure >::value();
  }
  static const char* value(const ::sensehat_ros::GetPressureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::GetPressureRequest> should match
// service_traits::DataType< ::sensehat_ros::GetPressure >
template<>
struct DataType< ::sensehat_ros::GetPressureRequest>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::GetPressure >::value();
  }
  static const char* value(const ::sensehat_ros::GetPressureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensehat_ros::GetPressureResponse> should match
// service_traits::MD5Sum< ::sensehat_ros::GetPressure >
template<>
struct MD5Sum< ::sensehat_ros::GetPressureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensehat_ros::GetPressure >::value();
  }
  static const char* value(const ::sensehat_ros::GetPressureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensehat_ros::GetPressureResponse> should match
// service_traits::DataType< ::sensehat_ros::GetPressure >
template<>
struct DataType< ::sensehat_ros::GetPressureResponse>
{
  static const char* value()
  {
    return DataType< ::sensehat_ros::GetPressure >::value();
  }
  static const char* value(const ::sensehat_ros::GetPressureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETPRESSURE_H
