// Generated by gencpp from file sensehat_ros/GetTemperatureResponse.msg
// DO NOT EDIT!


#ifndef SENSEHAT_ROS_MESSAGE_GETTEMPERATURERESPONSE_H
#define SENSEHAT_ROS_MESSAGE_GETTEMPERATURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensehat_ros
{
template <class ContainerAllocator>
struct GetTemperatureResponse_
{
  typedef GetTemperatureResponse_<ContainerAllocator> Type;

  GetTemperatureResponse_()
    : temperature(0.0)  {
    }
  GetTemperatureResponse_(const ContainerAllocator& _alloc)
    : temperature(0.0)  {
  (void)_alloc;
    }



   typedef double _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTemperatureResponse_

typedef ::sensehat_ros::GetTemperatureResponse_<std::allocator<void> > GetTemperatureResponse;

typedef boost::shared_ptr< ::sensehat_ros::GetTemperatureResponse > GetTemperatureResponsePtr;
typedef boost::shared_ptr< ::sensehat_ros::GetTemperatureResponse const> GetTemperatureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator1> & lhs, const ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensehat_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d36f909fc0be819c991c4abdee75a2b";
  }

  static const char* value(const ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d36f909fc0be819ULL;
  static const uint64_t static_value2 = 0xc991c4abdee75a2bULL;
};

template<class ContainerAllocator>
struct DataType< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensehat_ros/GetTemperatureResponse";
  }

  static const char* value(const ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 temperature\n"
;
  }

  static const char* value(const ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTemperatureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensehat_ros::GetTemperatureResponse_<ContainerAllocator>& v)
  {
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSEHAT_ROS_MESSAGE_GETTEMPERATURERESPONSE_H
