# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sensehat_ros/GetEnvironmentalRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetEnvironmentalRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "sensehat_ros/GetEnvironmentalRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# gets the current humidity and temperature from the humidity sensor and temperature and pressure from the pressure sensor
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetEnvironmentalRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sensehat_ros/GetEnvironmentalResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sensehat_ros.msg
import std_msgs.msg

class GetEnvironmentalResponse(genpy.Message):
  _md5sum = "59eda83d9763a27d7339a28eb5d390bf"
  _type = "sensehat_ros/GetEnvironmentalResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Environmental environmental

================================================================================
MSG: sensehat_ros/Environmental
# Hold data extracted from Sense HAT environmental sensors (humidity and pressure)
Header header
# Percentage of relative humidity 
float64 humidity
# Temperature in degrees Celsius from the humidity sensor
float64 temperature_from_humidity
# Temperature in degrees Celsius from the pressure sensor
float64 temperature_from_pressure
# Pressure in Millibars
float64 pressure

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['environmental']
  _slot_types = ['sensehat_ros/Environmental']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       environmental

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetEnvironmentalResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.environmental is None:
        self.environmental = sensehat_ros.msg.Environmental()
    else:
      self.environmental = sensehat_ros.msg.Environmental()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.environmental.header.seq, _x.environmental.header.stamp.secs, _x.environmental.header.stamp.nsecs))
      _x = self.environmental.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4d().pack(_x.environmental.humidity, _x.environmental.temperature_from_humidity, _x.environmental.temperature_from_pressure, _x.environmental.pressure))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.environmental is None:
        self.environmental = sensehat_ros.msg.Environmental()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.environmental.header.seq, _x.environmental.header.stamp.secs, _x.environmental.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.environmental.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.environmental.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.environmental.humidity, _x.environmental.temperature_from_humidity, _x.environmental.temperature_from_pressure, _x.environmental.pressure,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.environmental.header.seq, _x.environmental.header.stamp.secs, _x.environmental.header.stamp.nsecs))
      _x = self.environmental.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4d().pack(_x.environmental.humidity, _x.environmental.temperature_from_humidity, _x.environmental.temperature_from_pressure, _x.environmental.pressure))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.environmental is None:
        self.environmental = sensehat_ros.msg.Environmental()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.environmental.header.seq, _x.environmental.header.stamp.secs, _x.environmental.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.environmental.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.environmental.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.environmental.humidity, _x.environmental.temperature_from_humidity, _x.environmental.temperature_from_pressure, _x.environmental.pressure,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
class GetEnvironmental(object):
  _type          = 'sensehat_ros/GetEnvironmental'
  _md5sum = '59eda83d9763a27d7339a28eb5d390bf'
  _request_class  = GetEnvironmentalRequest
  _response_class = GetEnvironmentalResponse
